/**
 * Entitas Generated Extensions for echartstool
 *
 * do not edit this file
 */
 var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();

var echartstool;
(function (space) {
  'use strict';
  var Pool = entitas.Pool;
  var Entity = entitas.Entity;
  var CoreComponentIds;
  (function (CoreComponentIds) {
    CoreComponentIds[CoreComponentIds['ECharts'] = 0] = 'ECharts';
    CoreComponentIds[CoreComponentIds['EChartsOption'] = 1] = 'EChartsOption';
    CoreComponentIds[CoreComponentIds['DatGUI'] = 2] = 'DatGUI';
    CoreComponentIds[CoreComponentIds['SeriesType'] = 3] = 'SeriesType';
    CoreComponentIds[CoreComponentIds['TotalComponents'] = 4] = 'TotalComponents';
  })(CoreComponentIds = space.CoreComponentIds || (space.CoreComponentIds = {}));
  Entity.initialize(CoreComponentIds.TotalComponents, {"entities":128,"components":64});
  
  var EChartsComponent = /** @class */ (function () {
    function EChartsComponent() {}
    return EChartsComponent;
  }());
  space.EChartsComponent = EChartsComponent;
  
  var EChartsOptionComponent = /** @class */ (function () {
    function EChartsOptionComponent() {}
    return EChartsOptionComponent;
  }());
  space.EChartsOptionComponent = EChartsOptionComponent;
  
  var DatGUIComponent = /** @class */ (function () {
    function DatGUIComponent() {}
    return DatGUIComponent;
  }());
  space.DatGUIComponent = DatGUIComponent;
  
  var SeriesTypeComponent = /** @class */ (function () {
    function SeriesTypeComponent() {}
    return SeriesTypeComponent;
  }());
  space.SeriesTypeComponent = SeriesTypeComponent;
  
  var Pools = /** @class */ (function (_super) {
    __extends(Pools, _super);
    function Pools() {
      return _super !== null && _super.apply(this, arguments) || this;
    }
    Object.defineProperty(Pools, 'allPools', {
      get: function () {
        if (Pools._allPools == null) {
          Pools._allPools = [Pools.pool];
        }
        return Pools._allPools;
      },
      enumerable: false,
      configurable: true,
    });
    Object.defineProperty(Pools, 'pool', {
      get: function() {
        if (Pools._pool == null) {
          Pools._pool = new Pool(CoreComponentIds, CoreComponentIds.TotalComponents, false);
          entitas.viewer.VisualDebugging.init(Pools._pool);
        }
        return Pools._pool;
      },
      enumerable: false,
      configurable: true,
    });
    return Pools;
  }(Pool));
  space.Pools = Pools;
})(echartstool || (echartstool = {}));
(function () {
  'use strict';
  var Bag = entitas.utils.Bag;
  var Pool = entitas.Pool;
  var Entity = entitas.Entity;
  var Matcher = entitas.Matcher;
  var SingleEntityException = entitas.exceptions.SingleEntityException;

  var EChartsComponent = echartstool.EChartsComponent;
  var EChartsOptionComponent = echartstool.EChartsOptionComponent;
  var DatGUIComponent = echartstool.DatGUIComponent;
  var SeriesTypeComponent = echartstool.SeriesTypeComponent;
  
  var CoreComponentIds = echartstool.CoreComponentIds;
  
  
  /** @type {entitas.utils.Bag} */
  Entity._eChartsComponentPool = new Bag();
  // Bad Code
  // Entity._eChartsComponentPool.__proto__ = Bag.prototype;
  (function () {
    for (var i = 0; i < 64; i++) {
      Entity._eChartsComponentPool.add(new EChartsComponent());
    }
  })();
  Entity.clearEChartsComponentPool = function () {
    Entity._eChartsComponentPool.clear();
  };
  /** @type {echartstool.EChartsComponent} */
  Object.defineProperty(Entity.prototype, 'eCharts', {
    get: function () {
      return this.getComponent(CoreComponentIds.ECharts);
    }
  });
  /** @type {boolean} */
  Object.defineProperty(Entity.prototype, 'hasECharts', {
    get: function () {
      return this.hasComponent(CoreComponentIds.ECharts);
    }
  });
  /**
   * add
   * @param {HTMLDivElement} div
   * @param {any} myChart
   * @returns {entitas.Entity}
   */
  Entity.prototype.addECharts = function (div, myChart) {
    var component = Entity._eChartsComponentPool.size() > 0 ? Entity._eChartsComponentPool.removeLast() : new EChartsComponent();
    component.div = div;
    component.myChart = myChart;
    this.addComponent(CoreComponentIds.ECharts, component);
    return this;
  };
  /**
   * replace
   * @param {HTMLDivElement} div
   * @param {any} myChart
   * @returns {entitas.Entity}
   */
  Entity.prototype.replaceECharts = function (div, myChart) {
    var previousComponent = this.hasECharts ? this.eCharts : null;
    var component = Entity._eChartsComponentPool.size() > 0 ? Entity._eChartsComponentPool.removeLast() : new EChartsComponent();
    component.div = div;
    component.myChart = myChart;
    this.replaceComponent(CoreComponentIds.ECharts, component);
    if (previousComponent != null) {
      Entity._eChartsComponentPool.add(previousComponent);
    }
    return this;
  };
  /**
   * remove
   * @returns {entitas.Entity}
   */
  Entity.prototype.removeECharts = function () {
    var component = this.eCharts;
    this.removeComponent(CoreComponentIds.ECharts);
    Entity._eChartsComponentPool.add(component);
    return this;
  };
  
  /** @type {entitas.utils.Bag} */
  Entity._eChartsOptionComponentPool = new Bag();
  // Bad Code
  // Entity._eChartsOptionComponentPool.__proto__ = Bag.prototype;
  (function () {
    for (var i = 0; i < 64; i++) {
      Entity._eChartsOptionComponentPool.add(new EChartsOptionComponent());
    }
  })();
  Entity.clearEChartsOptionComponentPool = function () {
    Entity._eChartsOptionComponentPool.clear();
  };
  /** @type {echartstool.EChartsOptionComponent} */
  Object.defineProperty(Entity.prototype, 'eChartsOption', {
    get: function () {
      return this.getComponent(CoreComponentIds.EChartsOption);
    }
  });
  /** @type {boolean} */
  Object.defineProperty(Entity.prototype, 'hasEChartsOption', {
    get: function () {
      return this.hasComponent(CoreComponentIds.EChartsOption);
    }
  });
  /**
   * add
   * @param {any} option
   * @returns {entitas.Entity}
   */
  Entity.prototype.addEChartsOption = function (option) {
    var component = Entity._eChartsOptionComponentPool.size() > 0 ? Entity._eChartsOptionComponentPool.removeLast() : new EChartsOptionComponent();
    component.option = option;
    this.addComponent(CoreComponentIds.EChartsOption, component);
    return this;
  };
  /**
   * replace
   * @param {any} option
   * @returns {entitas.Entity}
   */
  Entity.prototype.replaceEChartsOption = function (option) {
    var previousComponent = this.hasEChartsOption ? this.eChartsOption : null;
    var component = Entity._eChartsOptionComponentPool.size() > 0 ? Entity._eChartsOptionComponentPool.removeLast() : new EChartsOptionComponent();
    component.option = option;
    this.replaceComponent(CoreComponentIds.EChartsOption, component);
    if (previousComponent != null) {
      Entity._eChartsOptionComponentPool.add(previousComponent);
    }
    return this;
  };
  /**
   * remove
   * @returns {entitas.Entity}
   */
  Entity.prototype.removeEChartsOption = function () {
    var component = this.eChartsOption;
    this.removeComponent(CoreComponentIds.EChartsOption);
    Entity._eChartsOptionComponentPool.add(component);
    return this;
  };
  
  /** @type {entitas.utils.Bag} */
  Entity._datGUIComponentPool = new Bag();
  // Bad Code
  // Entity._datGUIComponentPool.__proto__ = Bag.prototype;
  (function () {
    for (var i = 0; i < 64; i++) {
      Entity._datGUIComponentPool.add(new DatGUIComponent());
    }
  })();
  Entity.clearDatGUIComponentPool = function () {
    Entity._datGUIComponentPool.clear();
  };
  /** @type {echartstool.DatGUIComponent} */
  Object.defineProperty(Entity.prototype, 'datGUI', {
    get: function () {
      return this.getComponent(CoreComponentIds.DatGUI);
    }
  });
  /** @type {boolean} */
  Object.defineProperty(Entity.prototype, 'hasDatGUI', {
    get: function () {
      return this.hasComponent(CoreComponentIds.DatGUI);
    }
  });
  /**
   * add
   * @param {any} ui
   * @param {number} index
   * @returns {entitas.Entity}
   */
  Entity.prototype.addDatGUI = function (ui, index) {
    var component = Entity._datGUIComponentPool.size() > 0 ? Entity._datGUIComponentPool.removeLast() : new DatGUIComponent();
    component.ui = ui;
    component.index = index;
    this.addComponent(CoreComponentIds.DatGUI, component);
    return this;
  };
  /**
   * replace
   * @param {any} ui
   * @param {number} index
   * @returns {entitas.Entity}
   */
  Entity.prototype.replaceDatGUI = function (ui, index) {
    var previousComponent = this.hasDatGUI ? this.datGUI : null;
    var component = Entity._datGUIComponentPool.size() > 0 ? Entity._datGUIComponentPool.removeLast() : new DatGUIComponent();
    component.ui = ui;
    component.index = index;
    this.replaceComponent(CoreComponentIds.DatGUI, component);
    if (previousComponent != null) {
      Entity._datGUIComponentPool.add(previousComponent);
    }
    return this;
  };
  /**
   * remove
   * @returns {entitas.Entity}
   */
  Entity.prototype.removeDatGUI = function () {
    var component = this.datGUI;
    this.removeComponent(CoreComponentIds.DatGUI);
    Entity._datGUIComponentPool.add(component);
    return this;
  };
  
  /** @type {entitas.utils.Bag} */
  Entity._seriesTypeComponentPool = new Bag();
  // Bad Code
  // Entity._seriesTypeComponentPool.__proto__ = Bag.prototype;
  (function () {
    for (var i = 0; i < 64; i++) {
      Entity._seriesTypeComponentPool.add(new SeriesTypeComponent());
    }
  })();
  Entity.clearSeriesTypeComponentPool = function () {
    Entity._seriesTypeComponentPool.clear();
  };
  /** @type {echartstool.SeriesTypeComponent} */
  Object.defineProperty(Entity.prototype, 'seriesType', {
    get: function () {
      return this.getComponent(CoreComponentIds.SeriesType);
    }
  });
  /** @type {boolean} */
  Object.defineProperty(Entity.prototype, 'hasSeriesType', {
    get: function () {
      return this.hasComponent(CoreComponentIds.SeriesType);
    }
  });
  /**
   * add
   * @param {number} index
   * @param {string} type
   * @param {any} folder
   * @param {any[]} subFolder
   * @returns {entitas.Entity}
   */
  Entity.prototype.addSeriesType = function (index, type, folder, subFolder) {
    var component = Entity._seriesTypeComponentPool.size() > 0 ? Entity._seriesTypeComponentPool.removeLast() : new SeriesTypeComponent();
    component.index = index;
    component.type = type;
    component.folder = folder;
    component.subFolder = subFolder;
    this.addComponent(CoreComponentIds.SeriesType, component);
    return this;
  };
  /**
   * replace
   * @param {number} index
   * @param {string} type
   * @param {any} folder
   * @param {any[]} subFolder
   * @returns {entitas.Entity}
   */
  Entity.prototype.replaceSeriesType = function (index, type, folder, subFolder) {
    var previousComponent = this.hasSeriesType ? this.seriesType : null;
    var component = Entity._seriesTypeComponentPool.size() > 0 ? Entity._seriesTypeComponentPool.removeLast() : new SeriesTypeComponent();
    component.index = index;
    component.type = type;
    component.folder = folder;
    component.subFolder = subFolder;
    this.replaceComponent(CoreComponentIds.SeriesType, component);
    if (previousComponent != null) {
      Entity._seriesTypeComponentPool.add(previousComponent);
    }
    return this;
  };
  /**
   * remove
   * @returns {entitas.Entity}
   */
  Entity.prototype.removeSeriesType = function () {
    var component = this.seriesType;
    this.removeComponent(CoreComponentIds.SeriesType);
    Entity._seriesTypeComponentPool.add(component);
    return this;
  };
  
  
  /** @type {entitas.Matcher} */
  Matcher._matcherECharts = null;
  /** @type {entitas.Matcher} */
  Object.defineProperty(Matcher, 'ECharts', {
    get: function () {
      if (Matcher._matcherECharts == null) {
        Matcher._matcherECharts = Matcher.allOf(CoreComponentIds.ECharts);
      }
      return Matcher._matcherECharts;
    }
  });
  
  /** @type {entitas.Matcher} */
  Matcher._matcherEChartsOption = null;
  /** @type {entitas.Matcher} */
  Object.defineProperty(Matcher, 'EChartsOption', {
    get: function () {
      if (Matcher._matcherEChartsOption == null) {
        Matcher._matcherEChartsOption = Matcher.allOf(CoreComponentIds.EChartsOption);
      }
      return Matcher._matcherEChartsOption;
    }
  });
  
  /** @type {entitas.Matcher} */
  Matcher._matcherDatGUI = null;
  /** @type {entitas.Matcher} */
  Object.defineProperty(Matcher, 'DatGUI', {
    get: function () {
      if (Matcher._matcherDatGUI == null) {
        Matcher._matcherDatGUI = Matcher.allOf(CoreComponentIds.DatGUI);
      }
      return Matcher._matcherDatGUI;
    }
  });
  
  /** @type {entitas.Matcher} */
  Matcher._matcherSeriesType = null;
  /** @type {entitas.Matcher} */
  Object.defineProperty(Matcher, 'SeriesType', {
    get: function () {
      if (Matcher._matcherSeriesType == null) {
        Matcher._matcherSeriesType = Matcher.allOf(CoreComponentIds.SeriesType);
      }
      return Matcher._matcherSeriesType;
    }
  });
  
  
  
})();