export default {
    '4dG3R1': '2D Cloth',
    '4sf3Rn': 'Planet',
    '7lcyz8': 'KITTIES!!',
    ldfyzl: 'Rainier mood',
    MdG3Dd: 'Synaptic',
    WlKXRR: 'Day 61',
    XdXXz4: 'Motion Blur Visualization',
    Xls3D2: 'Frozen wasteland',
    flGyDd: 'Refraction + post proc',
    llj3Rz: '[NV15] Space Curvature',
    Ms2SD1: 'Seascape',
    XslGRr: 'Clouds',
    '3l23Rh': 'Protean clouds',
    Xds3zN: 'Raymarching - Primitives',
    '4ttSWf': 'Rainforest',
    XlfGRj: 'Star Nest',
    MdX3zr: 'Flame',
    fsjyR3: 'Lover',
    XsXXDn: 'Creation by Silexars',
    XsBXWt: 'Fractal Land',
    '4dcGW2': '(FAIL) expansive reaction-diffusion',
    MdX3Rr: 'Elevated',
    '4dfGzs': 'Voxel Edges',
    // https://www.shadertoy.com/results?query=&sort=love&from=12&num=12
    '3lsSzf': 'Happy Jumping',
    ltffzl: 'Heartfelt',
    ld3Gz2: 'Snail',
    llK3Dy: 'Rhodium liquid carbon',
    MdfBRX: 'The Drive Home',
    XsjXRm: 'Plasma Globe',
    MtX3Ws: 'Playing marble',
    MslGWN: 'Simplicity Galaxy',
    XsX3RB: 'Volcanic',
    '4dXGR4': 'Main Sequence Star',
    '4tdSWr': '2D Clouds',
    XsyGWV: 'Sirenian Dawn',
    // https://www.shadertoy.com/results?query=&sort=love&from=24&num=12
    Md23DV: 'GLSL 2D Tutorials',
    ldlcRf: 'Tribute - Journey! ',
    XtS3DD: 'Cloud Ten',
    ldXXDj: 'Music - Pirates',
    MdfGRX: 'Hell',
    Msl3Rr: 'Cubescape',
    XtGGRt: 'Auroras',
    XtVGD1: 'notebook drawings',
    MsGSRd: 'spilled',
    '4djSRW': 'Hash without Sine',
    tsKXR3: 'Multiscale MIP Fluid',
    //https://www.shadertoy.com/results?query=&sort=love&from=36&num=12
    WsSBzh: 'Selfie Girl',
    lsl3RH: 'Warping - procedural 2',
    Mld3Rn: 'Perspex Web Lattice',
    XlBSRz: 'VolumetricIntegration',
    NslGRN: 'Cube lines',
    lllBDM: 'Goo',
    MdlGW7: 'Cloudy Terrain',
    lsySzd: 'Volumetric explosion',
    XtlSD7: '[SIG15] Mario World 1-1',
    ldlXRS: 'Noise animation - Electric',
    '4sSfzK': '[SH17C] Physically Based Shading',
    '4ts3z2': 'Xyptonjtroz',
    // https://www.shadertoy.com/results?query=&sort=love&from=48&num=12
    ldl3W8: 'Voronoi - distances',
    llsGW7: '[2TC 15] Mystery Mountains',
    MsjSW3: 'Ether',
    MdlXz8: 'Tileable Water Caustic',
    llVXRd: 'Geodesic tiling',
    ll2GD3: 'Palettes',
    '4slGz4': 'Demo - Volumetric Lines',
    WtfyDj: 'Paint streams',
    MdXyzX: 'Very fast procedural ocean',
    MddGzf: 'Bricks Game',
    XdsGDB: 'Buoy',
    WdVXWy: '(FAIL) molten bismuth',
    // https://www.shadertoy.com/results?query=&sort=love&from=60&num=12
    '4tjGRh': 'Planet Shadertoy',
    '4dfXDn': '2d signed distance functions',
    '4tGfDW': "Chimera's Breath",
    XtsSWs: 'Skyline',
    XsfGWN: 'furball',
    lt3XDM: 'Tiny Planet: Earth',
    '4sl3Dr': 'Digital Brain',
    lscczl: 'The Universe Within',
    '4sjSW1': 'Remnant X',
    fstyD4: 'Coastal Landscape',
    XddSRX: 'Suture Fluid',
    MdGfzh: 'Himalayas',
    Xl2XRW: 'Where the River Goes',
    WlVyRV: 'Dry ice 2',
    MlXSWX: 'Abstract Corridor',
    Xsl3zX: 'galaxy3',
    Xdl3D2: 'Interstellar',
    Xtf3Rn: 'Generators',
    '4dl3zn': 'Bubbles',
    NddSWs: 'Taste of Noise 7',
    '4lf3Rj': 'Hot Shower',
    '4s23zz': 'Warping - procedural 1',
    '4sXGRM': 'Oceanic',
    Xd2GR3: 'Hexagons - distance',
    // https://www.shadertoy.com/results?query=&sort=love&from=84&num=12
    MscSzf: 'Noise Contour',
    '4dlyWX': 'Meta CRT',
    XlB3zV: 'Magnetismic',
    '4sK3RD': '(FAIL) Rock-Paper-Scissor-4D',
    lsKGDW: '(需要放大)oilArt',
    lslXDr: 'Atmospheric Scattering Sample',
    '4dSfRc': '[SH17C] Raymarching tutorial',
    '4dSBDt': 'Enscape Cube',
    ldSSzV: 'Wet stone',
    XlsGRs: 'jetstream',
    tsXBzS: 'fractal pyramid',
    lstSRS: '(FAIL) Gargantua With HDR Bloom',
    // https://www.shadertoy.com/results?query=&sort=love&from=96&num=12
    XllGW4: 'HOWTO: Ray Marching',
    '4sXBRn': 'Luminescence',
    MdBGzG: 'Canyon',
    wtfBDf: 'Warped Extruded Skewed Grid',
    '4ttGDH': 'Abstract Glassy Field',
    lsXGzH: 'Spout',
    Xd23Dh: 'Voronoise',
    XsXSWS: 'Fires',
    Xd23zh: 'Storm',
    tdjyzz: 'Tree in the wind',
    XtyXzW: 'Glitch transform',
    // https://www.shadertoy.com/results?query=&sort=love&from=108&num=12
    '4slGD4': 'Mountains',
    ldfSW2: 'sound - acid jam',
    XlSSzK: 'Sun surface',
    MsXGRf: 'Flames',
    MdKXzc: 'Supernova remnant',
    ldScDh: 'Greek Temple',
    MlKSWm: 'Sparks drifting',
    Mdf3z7: 'Menger Journey',
    XdlSDs: '[SIG2014] - Total Noob',
    Xt3SR4: 'Interactive thinks',
    Md3yRB: '(FAIL) Wythoff explorer',
    // https://www.shadertoy.com/results?query=&sort=love&from=120&num=12
    Ms3XWN: 'Pacman Game',
    ldj3Dm: 'Fish swimming',
    MdSGDm: 'Analytic Motionblur 2D',
    '4dSGW1': 'Grid of Cylinders',
    ltj3Wc: 'Brush Experiment 3',
    MsVfz1: 'Neon Lit Hexagons',
    Xs33Df: 'Desert Canyon',
    '4ds3zn': 'Apollonian',
    Xtf3zn: 'Tokyo',
    MsSGD1: 'Hand-drawn Sketch',
    '4sGSDw': '(FAIL) Sinuous',
    '4tByz3': 'Ladybug',
    // https://www.shadertoy.com/results?query=&sort=love&from=132&num=12
    '4dlGDN': 'Noise blur',
    '4s2SRt': 'Oblivion radar',
    fsXXzX: 'English Lane',
    MldXWX: '(FAIL) curtain and ball',
    XsfGzH: 'Star Nursery',
    wsByWV: '(FAIL) Voxel game Evolution',
    WtfGDX: 'Triangle Grid Contouring',
    Mdl3Rr: 'attic',
    '3ddGzn': 'Then and Before - PC4k by Altair',
    '4sS3zG': 'Dolphin',
    MdlXRS: 'Noise animation - Flow',
    // https://www.shadertoy.com/results?query=&sort=love&from=144&num=12
    MsB3WR: 'Misty Lake',
    llSyDh: 'Hexagonal Maze Flow',
    lslGWr: 'Simplicity',
    tt2XzG: 'Sphere Gears',
    WtSfWK: 'Hexagonal Grid Traversal - 3D',
    '4ldGz4': '[SH16B] Speed Drive 80',
    '4sX3Rs': 'Lens Flare Example',
    '4d2Xzw': 'Bokeh disc',
    MdXSzS: 'Galaxy of Universes',
    tdjBR1: '(FAIL) Volumetric lighting',
    ttKGDt: 'Phantom Star for CineShader',
    ldcSDB: 'Anisotropic Blur Image Warp',
    // https://www.shadertoy.com/results?query=&sort=love&from=156&num=12
    XlX3Rj: 'Circuits',
    lss3Df: 'Circle pattern',
    ldS3Wm: 'doski canady',
    '4sX3R2': 'Monster',
    '4dsXWn': 'Weather',
    Xst3Dj: 'Viscous Fingering',
    tsBSWD: 'Colored lines',
    '4ldGDB': 'Displacement with Dispersion',
    WdyGzy: 'Lattice Boltzmann ',
    lsf3RH: 'Ball Of Fire',
    '4sVczV': 'h e e e l i x',
    XsjXR1: 'Worms',
    wlSGWy: 'Raymarching in Raymarching',
    // https://www.shadertoy.com/results?query=&sort=love&from=168&num=12
    MsVXWW: 'Dusty nebula 4',
    '4sSSWz': 'starDust',
    Mt3GWs: 'Structured Vol Sampling',
    Xds3Rr: '(FAIL) Input - Sound',
    Xs2GDd: '[SH2014] Cellular',
    '4sfGWX': 'Wolfenstein 3D',
    '3tXXRn': 'Tentacle Object',
    '4dsXzM': 'Fovea detector',
    '4dsGD7': 'The Inversion Machine',
    '3sXyRN': 'Corridor Travel',
    '4tl3RM': 'Robin ',
    MsfGRr: 'Julia - Quaternion 1',
    // https://www.shadertoy.com/results?query=&sort=love&from=180&num=12
    MscXzn: 'IcePrimitives',
    '4slGzn': 'Rasterizer - Object',
    MslGRn: 'electron',
    '4sfGzS': 'Noise - value - 3D',
    ldtGWj: 'Precalculated Voronoi Heightmap',
    '4dsGzH': 'Waves',
    '4tlSzl': 'Combustible Voronoi',
    Mts3zM: 'Overly satisfying',
    XlfBR7: 'Tribute to Marc-Antoine Mathieu',
    fslcDS: 'Trippy Triangle',
    lsdGzN: 'Will it blend',
    lsXcWn: 'Smiley Tutorial',
    // https://www.shadertoy.com/results?query=&sort=love&from=192&num=12
    Xllfzl: 'Homeward',
    lscBW4: 'Old watch (IBL)',
    Mdf3zr: 'edge glow',
    ltj3zR: '[NV15] Impact',
    ldfGWn: 'Truchet Tentacles',
    XsfXW8: 'textured ellipsoids',
    '4s3SRN': 'Fractal Flythrough',
    Ns3XWf: 'Spiraled Layers',
    wtVyWK: 'Neural Stanford Bunny (5 kb)',
    ltlSWf: 'Flux Core',
    XtdGR7: '[SH16B] WIP: Warp Tunnel',
    MtcGDH: '(FAIL) [SH16C] Voxel Game',
    // https://www.shadertoy.com/results?query=&sort=love&from=204&num=12
    MdSczK: 'Multistep Fluid Simulation',
    XtX3Rr: 'Neptune Racing',
    '4sGSRV': 'Abstract Plane',
    XljGDz: 'Protophore',
    '3sySRK': 'CineShader Lava',
    '4slSWf': 'Bender',
    lsKfWd: '(SLOW) Quake / Introduction',
    XdcGWS: 'Shader Rally',
    Wtc3W2: 'Campfire at night',
    Mss3WN: 'MetaHexaBalls',
    lty3Rt: 'Pegasus Galaxy',
    XsfGRn: 'Heart - 2D',
    Md2GDw: 'mpeg artifacts',
    // https://www.shadertoy.com/results?query=&sort=love&from=216&num=12
    MlscDj: 'Neon World',
    lsBfDz: '[SH17A] Tiny Clouds',
    WdB3Dw: 'Bubble rings',
    llt3R4: 'Ray Marching: Part 1',
    lslXRS: 'Noise animation - Lava',
    '4ssXRX': 'noise distributions',
    MtKSWW: 'Dynamism',
    '4slyRs': 'Alien corridor',
    MlscWX: "Turn n' Burn",
    // https://www.shadertoy.com/results?query=&sort=love&from=228&num=12
    NlsXDH: 'Exit the Matrix',
    ttXGWH: 'Abstract Terrain Objects',
    ldccW4: 'Digital Rain',
    lsVBWy: 'Matrix Code',
    '7lKSWW': 'Truchet + Kaleidoscope FTW',
    ll2SRy: 'Transparent Cube Field',
    ltccRl: 'Outrun The Rain',
    wlVSDK: 'Danger Noodle',
    Xsc3R4: 'Cheap Cloud Flythrough',
    llXGR4: 'Antialiasing (sort of)',
    ttlXRf: 'in my crawl space',
    XsfGDn: 'Texture - Better Filtering',
    llySRh: 'iResolution, iMouse, iDate, etc',
    XdG3Wc: '(FAIL) pixelScreen',
    XdlGzH: 'Reprojection',
    MtKfRK: 'Data stream',
    // https://www.shadertoy.com/results?query=&sort=love&from=240&num=12
    MsdGzl: 'Basic Montecarlo',
    ldd3DB: 'Interactive Shoal of fish',
    ldjBW1: '[SH17A] Matrix rain',
    // https://www.shadertoy.com/results?query=&sort=newest&filter=
    DssSR4: 'circle Animation',
    mdXXRN: '[phreax] higher intelligence',
    wdfGW4: 'Descent 3D',
    mdXXzN: 'Radiation',
    mdfXRN: 'Unsharp Filter',
    DdXXzN: '(FAIL) Test Erosion Algo',
    cssXRH: 'circle with segments',
    csfXzN: 'Sea and moon',
    DdXSzN: '(buff改成1) Quake Palette experiments 6',
    csfSzN: 'Silk 2.0',
    DsfSzN: 'Silk 3.0',
    cdlSRH: 'Webcam: Water',
    slKfDt: 'Standard Operators (xy grids)',
    // https://www.shadertoy.com/results?query=&sort=newest&from=66948&num=12
    Ms2SWW: 'Deform - square tunnel',
    XsfGzn: '(0:ogm, 1:webm)Matte compositing',
    XdfGzn: 'Deform - rotozoom',
    '4dXGzn': 'Sun',
    XdXGzn: 'Deform - square tunnel II',
    XsXGzn: 'Clover',
    Xsf3Rn: 'Motion Blurred Texture',
    '4dX3Rn': 'Deform - flower',
    '4sfGRn': 'Radial Blur',
    '4dfGzn': 'Postprocessing',
    '4dfGRn': 'Julia - Traps 2',
    '4sXGzn': 'Deform - holes',
    '4df3Rn': 'Mandelbrot - smooth',
    '4sXGRn': 'Deform - relief tunnel',
    '4sX3Rn': 'Menger Sponge',
    MdfGRn: 'Vorotissue',
    Xdf3Rn: 'Deform - z invert',
    XdfGRn: 'Apple',
    XsX3Rn: 'Deform - fly',
    '4dXGRn': 'Deform - star',
    XdX3Rn: 'Kinderpainter (made in 2006)',
    MsfGRn: 'Burn',
    lsX3Rr: 'Nyan Cat',
    ldX3Rr: 'Yin Yang',
    lsfGRr: 'Beautypi',
    MdfGRr: 'Juliabulb - derivative',
    ltfSWn: 'Mandelbulb - derivative',
    lsXGzr: 'Noise bump',
    ldXGzr: 'Mouse Scroller',
    lsfGzr: 'Blobs',
    MdfGzr: 'Sierpinski plus',
    MsfGzr: 'To the road of ribbon',
    MdXGzr: 'Texture vortex',
    MsXGzr: 'Julia bonzaj mod1',
    '4slGRn': 'Alien in London',
    '4dsGRn': 'Ray tracer with volumetric light',
    '4dlGRn': 'Merry Christmas!',
    ldX3zr: 'Hypnotic ripples',
    MsX3zr: 'Cubes and Spheres',
    XslGRn: 'Nyan and Britney Take London',
    XslGzn: 'CPU intro!',
    Xss3zn: 'Gears',
    '4ssGzn': 'Fire2',
    XdlGzn: 'Rasterizer - Cube',
    Xdl3zn: 'Circles',
    '4sl3zr': 'pixelate',
    '4dl3zr': 'Sunset on the sea',
    Xdl3zr: 'Metaballs (Blobs)',
    XdlGRr: 'Julia - mare version',
    Xss3zr: 'video heightfield',
    '4ds3zr': 'voxels',
    Xsl3zr: 'little fluffy clouds',
    ldl3Rn: 'AOBench',
    ldsGRn: 'my first shader',
    Mds3Rn: 'The road to Hell',
    MslGzn: 'QuasiCrystal',
    Msl3Rn: 'Chains and Gears',
    Mss3Rn: 'Heart2',
    ldsGzn: 'Cube bird',
    lsl3Rn: 'R Tape loading error, 0:1',
    lslGzn: 'QuasicrystalRiff',
    MdlGzn: 'Torus Journey',
    MdsGzn: 'Nebelfeld',
    lssGzn: 'Coffee and Tablet',
    MdlGRr: 'Grid',
    MssGRr: 'Playing around',
    Mss3zn: 'Dark Chocolate Cave Plasma',
    MssGzn: 'Quadric #1',
    lds3zn: 'Ray tracing test',
    lslGRr: 'Sharpen',
    Mds3zn: 'Chromatic Aberration',
    lsl3zn: 'BlobBox',
    lss3zn: 'Multiple Effects',
    Xsl3zn: 'Warping - texture',
    lsl3Rr: 'IQ Clouds with beat',
    lslGzr: 'The Triforce',
    Mdl3zr: 'Round sound',
    Mdl3zn: 'depth',
    lsl3zr: 'codelifeclone@0:44',
    MssGzr: 'R.E.D. - final scene',
    MslGzr: 'Blueorange',
    Mds3Rr: 'Frosted Torus',
    '4df3R8': 'Audio Fl0wer',
    '4sX3R8': 'Magister',
    lds3zr: 'Ribbons',
    Msl3zr: 'led spectrum analyser',
    Xdf3R8: 'Fl0wer',
    Xsf3R8: 'Point light and Plane',
    '4sXGR8': 'string',
    lss3zr: 'Volume raycasting',
    XdX3R8: 'totorman-test1',
    XdlGzr: 'Gameboy ',
    XdfGz8: 'pyroclastic explosion',
    XsfGR8: 'Mandelbulb',
    XsX3z8: 'Video filters',
    '4dX3RH': 'Landscroller 1',
    '4sf3RH': 'spectrum circle starter',
    '4df3RH': 'jittering: Blur aliasing',
    '4sf3zH': 'Goa Theme',
    '4sfGRH': 'TextCandy',
    '4sfGz8': 'wallpaper',
    '4sXGzH': '4th Iteration',
    '4sXGRH': 'Mirror Cube',
    XdXGzH: 'jit.gl.pix exporting study',
    XdfGRH: 'Dancing Metalights',
    Xsf3RH: 'jit.gl.pix exporting test',
    XdfGzH: 'post: Screen Distort',
    MdsGzr: 'Mostly Harmless',
    '4sX3zH': "Blobs'n Goo",
    '4df3zH': 'half sphere lens distortion',
    Mdf3R8: '2D simple white point light',
    MdXGR8: 'Heart3',
    Msf3R8: 'Mandelbrot Test',
    MdfGR8: 'Infinite Sierpinski',
    MsXGR8: 'Split Prism',
    lsfGR8: 'Tunnel Tattoo',
    lsXGz8: 'Input - Time',
    lsX3R8: 'Balls, balls, balls!',
    ldl3zn: 'Timewarp',
    ldX3R8: 'Fake Global Illumination',
    ldfGR8: 'Test1',
    Xdf3zH: 'Flower Plasma',
    XslGR8: 'real eye ball',
    ldf3RH: 'Music ball',
    ldXGzH: 'Baghdad',
    ldX3RH: 'sad',
    Msf3RH: 'Triangle Fan',
    MsfGz8: 'Ray marching soft-shadows',
    MsX3zH: 'mothshader',
    MsX3RH: 'The Cave',
    MdXGRH: 'Twisted!',
    MdXGzH: '(SLOW) Blue Wall Clock Raytrace',
    '4dlGR8': 'ChaosTrend logo',
    XslGz8: 'Barrel Blur',
    ldf3zH: 'Globe',
    '4ssGR8': 'Soft Threshold Filter',
    XssGz8: 'post: Barrel Blur Chroma',
    Xdl3R8: 'UV Map Filter',
    '4ssGz8': 'Reactive Slime',
    '4slGR8': 'wowwow',
    '4dsGR8': 'Normal Map Filter',
    MtfGR8: 'Snowglobe_v2',
    '7tVSDh': 'Little Fibonacci Sphere',
    sldXWX: 'Snowman and The Tree',

    '4dl3z8': 'Radial Chroma Blur',
    // https://www.shadertoy.com/results?query=&sort=newest&from=66876&num=12
}
