export default {
    '4dG3R1': '2D Cloth',
    '4sf3Rn': 'Planet',
    '7lcyz8': 'KITTIES!!',
    ldfyzl: 'Rainier mood',
    MdG3Dd: 'Synaptic',
    WlKXRR: 'Day 61',
    XdXXz4: 'Motion Blur Visualization',
    Xls3D2: 'Frozen wasteland',
    flGyDd: 'Refraction + post proc',
    llj3Rz: '[NV15] Space Curvature',
    Ms2SD1: 'Seascape',
    XslGRr: 'Clouds',
    '3l23Rh': 'Protean clouds',
    Xds3zN: 'Raymarching - Primitives',
    '4ttSWf': 'Rainforest',
}
