export default {
    '4dG3R1': '2D Cloth',
    '4sf3Rn': 'Planet',
    '7lcyz8': 'KITTIES!!',
    ldfyzl: 'Rainier mood',
    MdG3Dd: 'Synaptic',
    WlKXRR: 'Day 61',
    XdXXz4: 'Motion Blur Visualization',
    Xls3D2: 'Frozen wasteland',
    flGyDd: 'Refraction + post proc',
    llj3Rz: '[NV15] Space Curvature',
    Ms2SD1: 'Seascape',
    XslGRr: 'Clouds',
    '3l23Rh': 'Protean clouds',
    '4ttSWf': 'Rainforest',
    XlfGRj: 'Star Nest',
    MdX3zr: 'Flame',
    fsjyR3: 'Lover',
    XsXXDn: 'Creation by Silexars',
    XsBXWt: 'Fractal Land',
    MdX3Rr: 'Elevated',
    '4dfGzs': 'Voxel Edges',
    '3lsSzf': 'Happy Jumping',
    ltffzl: 'Heartfelt',
    ld3Gz2: 'Snail',
    llK3Dy: 'Rhodium liquid carbon',
    MdfBRX: 'The Drive Home',
    XsjXRm: 'Plasma Globe',
    MtX3Ws: 'Playing marble',
    MslGWN: 'Simplicity Galaxy',
    XsX3RB: 'Volcanic',
    '4dXGR4': 'Main Sequence Star',
    '4tdSWr': '2D Clouds',
    XsyGWV: 'Sirenian Dawn',
    Md23DV: 'GLSL 2D Tutorials',
    ldlcRf: 'Tribute - Journey! ',
    XtS3DD: 'Cloud Ten',
    ldXXDj: 'Music - Pirates',
    MdfGRX: 'Hell',
    Msl3Rr: 'Cubescape',
    XtGGRt: 'Auroras',
    XtVGD1: 'notebook drawings',
    MsGSRd: 'spilled',
    '4djSRW': 'Hash without Sine',
    tsKXR3: 'Multiscale MIP Fluid',
    WsSBzh: 'Selfie Girl',
    Mld3Rn: 'Perspex Web Lattice',
    XlBSRz: 'VolumetricIntegration',
    NslGRN: 'Cube lines',
    lllBDM: 'Goo',
    MdlGW7: 'Cloudy Terrain',
    lsySzd: 'Volumetric explosion',
    XtlSD7: '[SIG15] Mario World 1-1',
    ldlXRS: 'Noise animation - Electric',
    '4sSfzK': '[SH17C] Physically Based Shading',
    '4ts3z2': 'Xyptonjtroz',
    llsGW7: '[2TC 15] Mystery Mountains',
    MsjSW3: 'Ether',
    MdlXz8: 'Tileable Water Caustic',
    llVXRd: 'Geodesic tiling',
    ll2GD3: 'Palettes',
    WtfyDj: 'Paint streams',
    MdXyzX: 'Very fast procedural ocean',
    MddGzf: 'Bricks Game',
    XdsGDB: 'Buoy',
    WdVXWy: '(FAIL) molten bismuth',
    '4tjGRh': 'Planet Shadertoy',
    '4dfXDn': '2d signed distance functions',
    '4tGfDW': "Chimera's Breath",
    XtsSWs: 'Skyline',
    lt3XDM: 'Tiny Planet: Earth',
    '4sl3Dr': 'Digital Brain',
    lscczl: 'The Universe Within',
    '4sjSW1': 'Remnant X',
    fstyD4: 'Coastal Landscape',
    XddSRX: 'Suture Fluid',
    MdGfzh: 'Himalayas',
    Xl2XRW: 'Where the River Goes',
    WlVyRV: 'Dry ice 2',
    MlXSWX: 'Abstract Corridor',
    Xsl3zX: 'galaxy3',
    Xdl3D2: 'Interstellar',
    Xtf3Rn: 'Generators',
    NddSWs: 'Taste of Noise 7',
    '4lf3Rj': 'Hot Shower',
    '4s23zz': 'Warping - procedural 1',
    Xd2GR3: 'Hexagons - distance',
    MscSzf: 'Noise Contour',
    '4dlyWX': 'Meta CRT',
    XlB3zV: 'Magnetismic',
    '4sK3RD': '(FAIL) Rock-Paper-Scissor-4D',
    lsKGDW: '(需要放大)oilArt',
    lslXDr: 'Atmospheric Scattering Sample',
    '4dSfRc': '[SH17C] Raymarching tutorial',
    '4dSBDt': 'Enscape Cube',
    ldSSzV: 'Wet stone',
    XlsGRs: 'jetstream',
    tsXBzS: 'fractal pyramid',
    lstSRS: '(FAIL) Gargantua With HDR Bloom',
    XllGW4: 'HOWTO: Ray Marching',
    '4sXBRn': 'Luminescence',
    MdBGzG: 'Canyon',
    wtfBDf: 'Warped Extruded Skewed Grid',
    '4ttGDH': 'Abstract Glassy Field',
    lsXGzH: 'Spout',
    Xd23Dh: 'Voronoise',
    XsXSWS: 'Fires',
    Xd23zh: 'Storm',
    tdjyzz: 'Tree in the wind',
    XtyXzW: 'Glitch transform',
    ldfSW2: 'sound - acid jam',
    XlSSzK: 'Sun surface',
    MsXGRf: 'Flames',
    MdKXzc: 'Supernova remnant',
    ldScDh: 'Greek Temple',
    MlKSWm: 'Sparks drifting',
    XdlSDs: '[SIG2014] - Total Noob',
    Xt3SR4: 'Interactive thinks',
    Md3yRB: 'Wythoff explorer',
    Ms3XWN: 'Pacman Game',
    ldj3Dm: 'Fish swimming',
    MdSGDm: 'Analytic Motionblur 2D',
    '4dSGW1': 'Grid of Cylinders',
    ltj3Wc: 'Brush Experiment 3',
    MsVfz1: 'Neon Lit Hexagons',
    Xs33Df: 'Desert Canyon',
    '4ds3zn': 'Apollonian',
    Xtf3zn: 'Tokyo',
    MsSGD1: 'Hand-drawn Sketch',
    '4sGSDw': '(FAIL) Sinuous',
    '4tByz3': 'Ladybug',
    '4s2SRt': 'Oblivion radar',
    fsXXzX: 'English Lane',
    MldXWX: '(FAIL) curtain and ball',
    XsfGzH: 'Star Nursery',
    wsByWV: '(FAIL) Voxel game Evolution',
    WtfGDX: 'Triangle Grid Contouring',
    '3ddGzn': 'Then and Before - PC4k by Altair',
    '4sS3zG': 'Dolphin',
    MdlXRS: 'Noise animation - Flow',
    MsB3WR: 'Misty Lake',
    llSyDh: 'Hexagonal Maze Flow',
    tt2XzG: 'Sphere Gears',
    WtSfWK: 'Hexagonal Grid Traversal - 3D',
    '4ldGz4': '[SH16B] Speed Drive 80',
    '4sX3Rs': 'Lens Flare Example',
    '4d2Xzw': 'Bokeh disc',
    MdXSzS: 'Galaxy of Universes',
    tdjBR1: '(FAIL) Volumetric lighting',
    ttKGDt: 'Phantom Star for CineShader',
    ldcSDB: 'Anisotropic Blur Image Warp',
    XlX3Rj: 'Circuits',
    lss3Df: 'Circle pattern',
    ldS3Wm: 'doski canady',
    '4sX3R2': 'Monster',
    '4dsXWn': 'Weather',
    Xst3Dj: 'Viscous Fingering',
    tsBSWD: 'Colored lines',
    '4ldGDB': 'Displacement with Dispersion',
    WdyGzy: 'Lattice Boltzmann ',
    lsf3RH: 'Ball Of Fire',
    '4sVczV': 'h e e e l i x',
    XsjXR1: 'Worms',
    wlSGWy: 'Raymarching in Raymarching',
    MsVXWW: 'Dusty nebula 4',
    '4sSSWz': 'starDust',
    Mt3GWs: 'Structured Vol Sampling',
    Xds3Rr: '(FAIL) Input - Sound',
    Xs2GDd: '[SH2014] Cellular',
    '4sfGWX': 'Wolfenstein 3D',
    '3tXXRn': 'Tentacle Object',
    '4dsXzM': 'Fovea detector',
    '4dsGD7': 'The Inversion Machine',
    '3sXyRN': 'Corridor Travel',
    '4tl3RM': 'Robin ',
    MsfGRr: 'Julia - Quaternion 1',
    MscXzn: 'IcePrimitives',
    MslGRn: 'electron',
    '4sfGzS': 'Noise - value - 3D',
    ldtGWj: 'Precalculated Voronoi Heightmap',
    '4dsGzH': 'Waves',
    '4tlSzl': 'Combustible Voronoi',
    Mts3zM: 'Overly satisfying',
    XlfBR7: 'Tribute to Marc-Antoine Mathieu',
    fslcDS: 'Trippy Triangle',
    lsdGzN: 'Will it blend',
    lsXcWn: 'Smiley Tutorial',
    Xllfzl: 'Homeward',
    lscBW4: 'Old watch (IBL)',
    Mdf3zr: 'edge glow',
    ltj3zR: '[NV15] Impact',
    XsfXW8: 'textured ellipsoids',
    '4s3SRN': 'Fractal Flythrough',
    Ns3XWf: 'Spiraled Layers',
    wtVyWK: 'Neural Stanford Bunny (5 kb)',
    ltlSWf: 'Flux Core',
    XtdGR7: '[SH16B] WIP: Warp Tunnel',
    MtcGDH: '[SH16C] Voxel Game',
    MdSczK: 'Multistep Fluid Simulation',
    XtX3Rr: 'Neptune Racing',
    '4sGSRV': 'Abstract Plane',
    XljGDz: 'Protophore',
    '3sySRK': 'CineShader Lava',
    '4slSWf': 'Bender',
    lsKfWd: '(SLOW) Quake / Introduction',
    XdcGWS: 'Shader Rally',
    Wtc3W2: 'Campfire at night',
    Mss3WN: 'MetaHexaBalls',
    lty3Rt: 'Pegasus Galaxy',
    XsfGRn: 'Heart - 2D',
    Md2GDw: 'mpeg artifacts',
    MlscDj: 'Neon World',
    lsBfDz: '[SH17A] Tiny Clouds',
    WdB3Dw: 'Bubble rings',
    llt3R4: 'Ray Marching: Part 1',
    lslXRS: 'Noise animation - Lava',
    '4ssXRX': 'noise distributions',
    MtKSWW: 'Dynamism',
    '4slyRs': 'Alien corridor',
    MlscWX: "Turn n' Burn",
    NlsXDH: 'Exit the Matrix',
    ttXGWH: 'Abstract Terrain Objects',
    ldccW4: 'Digital Rain',
    lsVBWy: 'Matrix Code',
    '7lKSWW': 'Truchet + Kaleidoscope FTW',
    ll2SRy: 'Transparent Cube Field',
    ltccRl: 'Outrun The Rain',
    wlVSDK: 'Danger Noodle',
    Xsc3R4: 'Cheap Cloud Flythrough',
    llXGR4: 'Antialiasing (sort of)',
    ttlXRf: 'in my crawl space',
    llySRh: 'iResolution, iMouse, iDate, etc',
    XdG3Wc: '(FAIL) pixelScreen',
    XdlGzH: 'Reprojection',
    MtKfRK: 'Data stream',
    MsdGzl: 'Basic Montecarlo',
    ldd3DB: 'Interactive Shoal of fish',
    ldjBW1: '[SH17A] Matrix rain',
    DssSR4: 'circle Animation',
    mdXXRN: '[phreax] higher intelligence',
    wdfGW4: 'Descent 3D',
    mdXXzN: 'Radiation',
    mdfXRN: 'Unsharp Filter',
    DdXXzN: '(FAIL) Test Erosion Algo',
    cssXRH: 'circle with segments',
    csfXzN: 'Sea and moon',
    DdXSzN: '(buff改成1) Quake Palette experiments 6',
    csfSzN: 'Silk 2.0',
    DsfSzN: 'Silk 3.0',
    cdlSRH: 'Webcam: Water',
    slKfDt: 'Standard Operators (xy grids)',
    Ms2SWW: 'Deform - square tunnel',
    XsfGzn: '(0:ogm, 1:webm)Matte compositing',
    XdfGzn: 'Deform - rotozoom',
    '4dXGzn': 'Sun',
    XdXGzn: 'Deform - square tunnel II',
    XsXGzn: 'Clover',
    Xsf3Rn: 'Motion Blurred Texture',
    '4dX3Rn': 'Deform - flower',
    '4sfGRn': 'Radial Blur',
    '4dfGzn': 'Postprocessing',
    '4dfGRn': 'Julia - Traps 2',
    '4sXGzn': 'Deform - holes',
    '4df3Rn': 'Mandelbrot - smooth',
    '4sXGRn': 'Deform - relief tunnel',
    '4sX3Rn': 'Menger Sponge',
    MdfGRn: 'Vorotissue',
    Xdf3Rn: 'Deform - z invert',
    XdfGRn: 'Apple',
    XsX3Rn: 'Deform - fly',
    '4dXGRn': 'Deform - star',
    XdX3Rn: 'Kinderpainter (made in 2006)',
    MsfGRn: 'Burn',
    lsX3Rr: 'Nyan Cat',
    ldX3Rr: 'Yin Yang',
    lsfGRr: 'Beautypi',
    MdfGRr: 'Juliabulb - derivative',
    ltfSWn: 'Mandelbulb - derivative',
    lsXGzr: 'Noise bump',
    ldXGzr: 'Mouse Scroller',
    lsfGzr: 'Blobs',
    MdfGzr: 'Sierpinski plus',
    MsfGzr: 'To the road of ribbon',
    MdXGzr: 'Texture vortex',
    MsXGzr: 'Julia bonzaj mod1',
    '4slGRn': 'Alien in London',
    '4dsGRn': 'Ray tracer with volumetric light',
    '4dlGRn': 'Merry Christmas!',
    ldX3zr: 'Hypnotic ripples',
    MsX3zr: 'Cubes and Spheres',
    XslGRn: 'Nyan and Britney Take London',
    XslGzn: 'CPU intro!',
    Xss3zn: 'Gears',
    '4ssGzn': 'Fire2',
    XdlGzn: 'Rasterizer - Cube',
    Xdl3zn: 'Circles',
    '4sl3zr': 'pixelate',
    '4dl3zr': 'Sunset on the sea',
    Xdl3zr: 'Metaballs (Blobs)',
    XdlGRr: 'Julia - mare version',
    Xss3zr: 'video heightfield',
    '4ds3zr': 'voxels',
    Xsl3zr: 'little fluffy clouds',
    ldl3Rn: 'AOBench',
    ldsGRn: 'my first shader',
    Mds3Rn: 'The road to Hell',
    MslGzn: 'QuasiCrystal',
    Msl3Rn: 'Chains and Gears',
    Mss3Rn: 'Heart2',
    ldsGzn: 'Cube bird',
    lsl3Rn: 'R Tape loading error, 0:1',
    lslGzn: 'QuasicrystalRiff',
    MdlGzn: 'Torus Journey',
    MdsGzn: 'Nebelfeld',
    lssGzn: 'Coffee and Tablet',
    MdlGRr: 'Grid',
    MssGRr: 'Playing around',
    Mss3zn: 'Dark Chocolate Cave Plasma',
    MssGzn: 'Quadric #1',
    lds3zn: 'Ray tracing test',
    lslGRr: 'Sharpen',
    Mds3zn: 'Chromatic Aberration',
    lsl3zn: 'BlobBox',
    lss3zn: 'Multiple Effects',
    Xsl3zn: 'Warping - texture',
    lsl3Rr: 'IQ Clouds with beat',
    lslGzr: 'The Triforce',
    Mdl3zr: 'Round sound',
    Mdl3zn: 'depth',
    lsl3zr: 'codelifeclone@0:44',
    MssGzr: 'R.E.D. - final scene',
    MslGzr: 'Blueorange',
    Mds3Rr: 'Frosted Torus',
    '4df3R8': 'Audio Fl0wer',
    '4sX3R8': 'Magister',
    lds3zr: 'Ribbons',
    Msl3zr: 'led spectrum analyser',
    Xdf3R8: 'Fl0wer',
    Xsf3R8: 'Point light and Plane',
    '4sXGR8': 'string',
    lss3zr: 'Volume raycasting',
    XdX3R8: 'totorman-test1',
    XdlGzr: 'Gameboy ',
    XdfGz8: 'pyroclastic explosion',
    XsfGR8: 'Mandelbulb',
    XsX3z8: 'Video filters',
    '4dX3RH': 'Landscroller 1',
    '4sf3RH': 'spectrum circle starter',
    '4df3RH': 'jittering: Blur aliasing',
    '4sf3zH': 'Goa Theme',
    '4sfGRH': 'TextCandy',
    '4sfGz8': 'wallpaper',
    '4sXGzH': '4th Iteration',
    '4sXGRH': 'Mirror Cube',
    XdXGzH: 'jit.gl.pix exporting study',
    XdfGRH: 'Dancing Metalights',
    Xsf3RH: 'jit.gl.pix exporting test',
    XdfGzH: 'post: Screen Distort',
    MdsGzr: 'Mostly Harmless',
    '4sX3zH': "Blobs'n Goo",
    '4df3zH': 'half sphere lens distortion',
    Mdf3R8: '2D simple white point light',
    MdXGR8: 'Heart3',
    Msf3R8: 'Mandelbrot Test',
    MdfGR8: 'Infinite Sierpinski',
    MsXGR8: 'Split Prism',
    lsfGR8: 'Tunnel Tattoo',
    lsXGz8: 'Input - Time',
    lsX3R8: 'Balls, balls, balls!',
    ldl3zn: 'Timewarp',
    ldX3R8: 'Fake Global Illumination',
    ldfGR8: 'Test1',
    Xdf3zH: 'Flower Plasma',
    XslGR8: 'real eye ball',
    ldf3RH: 'Music ball',
    ldXGzH: 'Baghdad',
    ldX3RH: 'sad',
    Msf3RH: 'Triangle Fan',
    MsfGz8: 'Ray marching soft-shadows',
    MsX3zH: 'mothshader',
    MsX3RH: 'The Cave',
    MdXGRH: 'Twisted!',
    MdXGzH: '(SLOW) Blue Wall Clock Raytrace',
    '4dlGR8': 'ChaosTrend logo',
    XslGz8: 'Barrel Blur',
    ldf3zH: 'Globe',
    '4ssGR8': 'Soft Threshold Filter',
    XssGz8: 'post: Barrel Blur Chroma',
    Xdl3R8: 'UV Map Filter',
    '4ssGz8': 'Reactive Slime',
    '4slGR8': 'wowwow',
    '4dsGR8': 'Normal Map Filter',
    MtfGR8: 'Snowglobe_v2',
    '7tVSDh': 'Little Fibonacci Sphere',
    sldXWX: 'Snowman and The Tree',
    '4dl3z8': 'Radial Chroma Blur',
    lslGR8: 'Grassy',
    Xsl3z8: 'Color Zebra',
    MslGR8: 'dithering: Color Banding Removal',
    XslGzH: 'interference',
    '4slGRH': 'Primes',
    XdsGzH: 'Basic Deform Shader',
    XdX3z8: 'Weirdness',
    MssGR8: 'Basic Edge Detection',
    XdlGz8: 'Emboss',
    Xdl3zH: 'Bubbling Puls',
    '4ssGzH': 'Hysto',
    '4sl3RH': 'Ray*Bert',
    Msl3R8: 'Mandel Fire',
    lssGz8: 'Metamaterial',
    MdsGz8: 'Marching Cubes',
    lssGR8: 'Pulsing Interference',
    lsf3zr: 'Columns and Lights',
    Mds3R8: 'Lyapunov',
    lss3R8: 'Cel Shading',
    ldlGz8: 'PhongShading',
    lds3R8: 'motion',
    ldl3R8: 'Edge filter',
    Mss3R8: 'Julia - Distance 1',
    MsXGzH: 'Thumper',
    lssGzH: 'mouse',
    lssGRH: 'Red Planet',
    lslGRH: 'NanoTubes',
    lsl3zH: 'Triangle field',
    Msl3RH: 'Derivatives - test',
    lds3RH: 'FakeRipple',
    MssGzH: 'Paintballs',
    ldsGzH: 'LOL CRAP',
    ldl3zr: 'Möbius balls',
    Msl3z8: 'Blurred ball',
    MslGRH: 'Binary Serpents',
    MdsGzH: 'calendar',
    lds3zH: 'WaveTransion',
    '4sX3R4': 'Particle Tracing',
    lds3z8: '1000 Spheres remake from 1995',
    '4sfGR4': 'mod filter',
    ldlGR8: 'RM Cell Shading',
    Xsf3R4: 'CircleMapping',
    XsXGR4: 'The Needle',
    Xdf3R4: 'Pseudo Volumetric',
    Mss3zH: 'Input - Mouse',
    Msl3zH: 'Blue serpents',
    '4df3R4': 'Ocean on Fire',
    '4dfGz8': 'Androids',
    Xdf3z4: '3D Spheres !',
    XsX3R4: 'Cells',
    XdX3z4: 'Simple Modulation Example',
    XdXGz4: 'separateRGB',
    Xdf3RN: 'Contrast',
    Xsf3RN: 'Night vision device',
    XsfGz4: 'Sky in the Pi',
    '4dfGz4': 'Voxel Tyre',
    MsXGz8: 'Isolines',
    '4sX3RN': 'NoiseWarp',
    Mdl3Rr: 'attic',
    '4sf3RN': 'Numbers',
    XsX3zN: 'Cube Attack',
    MdXGR4: 'Dream Paint',
    XdfGzN: ':V',
    lsX3R4: 'Simplest raytracing',
    Mdl3RH: 'Iterations - trigonometric',
    Msf3R4: 'spectrum_mod',
    XdX3zN: 'Flying Logo',
    MsXGz4: 'Cubemaps',
    lsf3z4: 'BadTV',
    lsf3R4: 'Wavy Texture Shader',
    ldXGz4: 'water-horizontal',
    lsX3z4: 'Cells on Fire',
    ldfGz4: 'Blur Banding Redux',
    ldf3RN: 'Bokeh blur',
    '4slGzn': 'Rasterizer - Object',
    '4dXGRN': 'Infinite repetition',
    Xdl3R4: 'Cell',
    Xss3R4: 'Flower shader',
    XdsGR4: 'etched #23',
    Xds3RN: 'Beer',
    MsX3zN: 'Test Refraction',
    Mdf3RN: 'Audio heightfield 2',
    lsXGzN: 'Salmiakki',
    ldf3zN: 'Borgo',
    ldXGzN: 'Audio heightfield 1',
    '4ss3R4': 'More Aliasing please',
    '4ssGR4': 'Snake Eye',
    '4slGRN': 'Circling Spheres',
    '4dl3R4': 'Snowy',
    '4dl3z4': 'Smooth Waveform',
    '4slGz4': 'Demo - Volumetric Lines',
    Xds3zN: 'Raymarching - Primitives',
    '4sl3z4': 'Moonlight',
    XssGzN: 'TEKITOU',
    Mss3R4: 'Kaleidoscope of rotating border',
    Mdl3z8: 'RedSpace',
    MdfGz4: 'CRT',
    '4ss3z4': 'Shady Building',
    lslGR4: 'Chalk stroke',
    '4ss3RN': 'wave',
    '4slGzN': 'My SpotLight',
    '4sl3zN': 'RINGS',
    '4ds3RN': 'Cubemap Shading',
    '4dcGW2': '(FAIL) expansive reaction-diffusion',
    MdlGz4: 'Minecraft Blocks',
    lds3z4: 'Chocolate mountain',
    lslGRN: 'Grid Barrel Distortion',
    Mdl3z4: 'box filter edge detection',
    MdlGzN: 'Áttétel',
    lds3RN: 'Mercury',
    MslGz4: '3d blobs',
    '4sl3zn': 'Siggraph logo',
    '4sl3z8': '(FAIL) The Endless Track',
    lsl3zN: 'State of the Art',
    XsXGRM: '2d blobs',
    Xss3zN: 'Minefield',
    Msl3zN: 'Smooth of the Art',
    Mds3zN: 'Intereference with colors',
    XdXGRM: 'Grid runner',
    Mss3zN: 'Cheap bokeh effect',
    Mss3RN: 'Raymarching simple',
    MslGzN: 'C64 plasma',
    Mdl3zN: 'C64 raytracer',
    '4sXGRM': 'Oceanic',
    '4dXGRM': 'flying steel cubes',
    '4sX3RM': '2d tunnel',
    ldl3zN: 'Piano',
    XsfGzM: 'Nyan',
    XsX3R7: 'Mapping',
    XsXGR7: 'Shock Wave',
    Xdf3RM: 'Áttételek',
    XdfGR7: 'blood sample',
    Xdf3zM: 'Shard',
    XdXGR7: 'water drops',
    '4sfGR7': 'Abandoned base on Mars',
    '4dfGzM': 'Waterfall',
    '4sf3RM': 'Island',
    ldXGRM: 'spot light',
    MdX3RM: 'Perlin Planet',
    '4sX3z7': 'Tunnel Effect',
    XdXGz7: 'The Mystery Vortex',
    XsfGz7: 'attract tickler',
    XsX3z7: 'Kaleidoscopic Journey',
    lsX3zM: 'Tiles',
    ldX3zM: 'Riley',
    MdXGz4: 'Nautilus',
    MsX3RM: '2d distort',
    '4sfGz7': 'Trumpet',
    lsl3RH: 'Warping - procedural 2',
    lsXGR7: 'audiobrot',
    ldXGz7: '2d water shader',
    XsfGR7: 'The Cross',
    MsXGzM: 'Voronoi - rocks',
    MsXGz7: 'soundbrot',
    MsfGzN: 'Glass Cubes',
    Msf3zM: 'brot',
    MsfGz7: 'Shatter',
    MsfGR7: 'Foggy Fields',
    Msf3R7: 'rubber goo of pastel',
    MdX3R7: 'julia explorer',
    Mdf3z7: 'Menger Journey',
    Msf3z7: 'Metameatballs',
    lsXGzM: 'Auralights',
    '4slGRM': 'Water',
    XslGRM: 'Halftone',
    XdsGR7: 'Colors2',
    Mdf3zM: "Escher's prentententoonstelling",
    '4dlGR7': 'WaveMotion',
    '4sXGz7': 'Evil',
    '4df3R7': 'Circular Blur',
    '4dlGzM': 'triple shape',
    '4ss3zM': 'Trial2',
    '4ds3RM': 'flipbrot',
    '4dlGRM': 'Starburst',
    Xds3zM: 'Stack',
    XslGz7: 'Kaleidoscope Ett',
    XdsGz7: 'Kaleidoscope TvÃ¥',
    Msf3z4: 'Reprojection II',
    '4ssGR7': 'Plasma 90x',
    '4ssGz7': 'hexagon',
    '4ss3R7': 'HenBrotFinal',
    '4slGz7': 'Old Warehouse',
    lssGRM: 'Angels',
    lslGRM: 'Nyanrotozoom',
    lssGR7: 'Glass Walls 1',
    MdsGR7: 'Chewbacka 2',
    ldlGzM: 'Arrangements',
    lsl3zM: 'Long slender flexible things',
    ldsGR7: 'DOH!',
    XssGzn: 'Hilbert curve  v0.9',
    MslGzM: '2D Cell PostEffect',
    Mds3R7: 'Lollypop (sound)',
    Mdl3R7: 'Psychadelic',
    '4sX3z4': 'Chromatic Aberration Effect',
    ldlGz7: 'Doilychain',
    lss3R7: 'Alhambra on lsd (sound)',
    Msl3zM: 'Mars Fleet',
    '4dXGWn': 'fractal kaleidoscope',
    lds3z7: 'random noise',
    ldl3R7: 'Cyclonic Sphere',
    XsX3Wn: 'Time warp',
    Xdf3z8: 'LightCycle',
    XdX3Wn: 'Plasma',
    MslGz7: 'MandelOnTexture',
    '4sf3Wn': 'Nauseator (sound)',
    '4dX3Wn': 'Tunnel of doom',
    XsfGDn: 'Texture - Better Filtering',
    XsXGDn: 'Unnamed (sound)',
    XdfGDn: 'Colored Circles',
    '4dXGDn': 'Invaders',
    '4df3Dn': 'bicubic',
    XdXGDn: 'Many mouths to feed',
    XdXGWr: "Akiyoshi's Snakes Illusion",
    XdX3Wr: 'warptest',
    '4sf3Dn': 'Brain Storm',
    '4sXGDn': 'Folded gold',
    '4dfGWr': 'Kaleidoscope tre - bendy',
    '4sX3Wr': 'Water columns',
    '4dXGWr': 'Shiny taffy',
    '4sXGDr': 'DF 2D visualization',
    lsXGWn: 'Simple Bloom/Glow (white)',
    XsfGDr: 'Diamond #1',
    ldsGRM: 'Clock',
    Xsf3Dr: 'Texture - HW interpolation',
    XsX3Dr: 'Palindrome',
    XdfGDr: 'Barbarella',
    Mss3zM: 'Insect',
    MdXGWn: 'glitch video',
    '4dfGDr': 'Tunnel #1',
    '4sf3Dr': 'CRT Effect',
    ldfGWn: 'Truchet Tentacles',
    MsfGWn: 'Circular Tex-Magnification',
    lsfGWn: 'Blur: Poisson Disc',
    ldX3Wn: 'Dancing pixels',
    MdfGWn: 'Ellipse - Distance Estimation',
    lsf3Dn: 'Rays of Blinding Light',
    lsX3Wr: 'panda design',
    lsX3Dn: 'Sharpening filter',
    lsX3Wn: 'osmo',
    ldXGDn: 'Epileptor #2',
    ldfGWr: 'Technicolor Swirl',
    XtX3Rj: 'Rubik',
    ldX3Dn: 'myTest',
    Msf3Dn: 'Sound Flower',
    MsXGDn: 'Visualization Experiment #1',
    MdXGDr: 'Data Transfer',
    MdfGDr: 'Bubblefield.',
    MdX3Dn: 'Recogniser',
    '4dl3z7': 'Haunted Forest',
    MdX3Dr: 'Crosshatch',
    '4dlGWn': 'Fractals: Mandelbrot',
    lsfGWr: 'tet',
    '4slGDn': 'Filter: Desaturation',
    Xss3Wn: 'just some clouds',
    ldXGDr: 'Flatland',
    '4ssGWn': 'Boing Ball',
    Mdf3Dr: 'Outrun',
    XslGWn: 'Anaglyph Elevated',
    Msf3Wr: 'Fractal Noise',
    '4slGWn': 'Texture - LOD',
    '4dsGDn': 'Chromatic Aberration Filter',
    '4dl3zn': 'Bubbles',
    '4dlGDr': 'Filter: Box Blur',
    MsXGWr: 'Mike',
    Mdf3Dn: 'CMYK Halftone',
    '4ds3Dn': 'Voronoi',
    '4ss3Dn': 'Mandlebulb Evolution',
    '4sl3Dn': 'A Cloud',
    lssGDn: 'Pseudo 3D Tunnel',
    lssGWn: 'Easter Egg',
    ldsGWn: 'Random raytracer (unfinished)',
    XssGDr: 'Classic tunnel effect',
    ldsGDn: 'Just snow',
    Xss3Wr: 'Candy',
    lsl3Wn: 'Gouraud triangle',
    Xss3Dr: 'Procedural Checkerboard',
    Mds3Wn: 'Digital Heart',
    XdsGDr: 'Julia fractal',
    XslGDr: 'Glow hack',
    MslGWn: '2D Distortion hack1',
    Msf3Dr: 'Near miss!',
    MdlGWn: 'balls are touching',
    '4slGDr': 'Bubbles!',
    '4ss3Dr': 'Edge Detection (Sobel kernels)',
    ldf3Dr: 'Stereogram',
    lds3Dn: 'Eclipse',
    lslGWr: 'Simplicity',
    lssGDr: 'Simple plane walkthrough',
    Mss3Dr: 'AudioSurf',
    Msl3Dr: 'SoundMarch',
    Xss3z4: 'Terrain + Sun',
    XsXGD8: 'Sorry, I went abstract',
    '4sf3W8': 'Simple Edge Detector',
    Mds3Wr: 'Burning planet',
    ldXGzM: 'perlin terrain',
    ldf3W8: 'Rainbow Lights',
    XsX3WH: 'Peaks and fog',
    '4dfGDH': 'Bilateral filter',
    ldX3W8: 'Sinus Color Curve ',
    Xdf3D8: 'claw',
    XdfGDH: 'Gaussian Blur',
    MdXGW8: 'blendashit',
    '4df3D8': 'Image - Audrey',
    '4sXGDH': 'Lemminvade',
    '4dXGWH': 'Nyancat',
    lsfGWH: 'starsbackground',
    ldfGWH: 'colored night sky stars',
    Mdf3W8: 'Color Fader',
    lsXGWH: '2D Night sky flickering stars',
    lsX3WH: 'A lot of spheres',
    lsf3WH: 'Noise - value - 2D',
    ldfGD8: 'Noise experiment #2',
    ldX3D8: 'cloned: rainbow spectrum',
    XdXGW8: 'Noise - gradient - 2D',
    Mds3zM: 'Sonic Rainboom',
    MsXGD8: 'Noise experiment',
    MdfGW8: 'wat tracing',
    MsX3WH: 'Mona Lisa in triangles',
    lsfGDH: 'roto wobble',
    Msf3DH: 'perlin noise sphere',
    '4dsGW8': 'Segmented Spheres',
    ldX3DH: 'old school lens effect',
    lsf3DH: 'reflecting floor',
    ldf3DH: 'spike donut',
    '4dlGW8': 'Eye sketch',
    MsfGDH: 'raster bars',
    Msf3WH: 'Noise - simplex - 2D',
    Mdf3DH: 'reflecting cube',
    MsX3DH: 'wobbling cube',
    MdXGDH: 'old school plasma',
    lsX3DH: 'More spheres',
    Xds3W8: 'Simple Convolve',
    XsXGDH: 'sad robot',
    Xdl3WH: 'Brick Vortex',
    lslGDn: 'Shadertoy',
    XdsGWH: 'Mars demo',
    '4slGWH': 'Fractal Nyancat',
    XssGD8: 'Wiggly (try mouse)',
    Xdl3D8: 'Old video',
    Xds3Dn: 'Implicit Curve Example',
    MsfGzM: 'Two Tweets',
    XdsGD8: 'blobs and scanline',
    lssGWH: 'Relictemp',
    lslGW8: 'Bump mapping',
    ldl3W8: 'Voronoi - distances',
    Xsl3WH: 'Sine Line',
    Xsl3DH: 'Shockwaves',
    MslGD8: 'Voronoi - basic',
    '4sfGWr': 'Voronoitoy',
    MslGW8: 'ScrollMap',
    '4sl3DH': 'Simple Hue Rotation',
    '4ss3DH': 'hearts',
    '4ds3WH': 'HypnoSwirlâ„¢',
    '4dl3W8': 'Phoning Home',
    lslGDH: 'Bump to normal',
    lds3WH: 'Spikeball Test',
    lds3DH: 'Shapeshifter',
    ldl3DH: 'Britney in space',
    lds3D8: 'Oculus rift & Spheres',
    Xsl3D8: 'Pacman',
    Msl3WH: 'Warp speed',
    MdsGDH: 'Polychora (4D)',
    '4dl3WH': 'Little PathTracing',
    '4dXGW4': 'RT',
    XsXGW4: 'guitar',
    lssGDH: 'Leaf',
    XsfGWN: 'furball',
    XdfGDN: 'Wobbly Chrome',
    XsX3D4: 'TriWell',
    XdfGW4: 'Regular 4D Polytopes',
    Xdf3WN: 'first demo',
    XdX3W7: 'Sine Waves 2',
    XdX3D4: 'Gamma and quantization',
    XdXGD4: 'Tunnel Me Softly',
    Mds3D8: 'Curiosity',
    '4sfGWN': 'Dropout',
    '4sX3WN': 'Fun with Derivatives',
    '4sX3W4': 'Circle_Mouse',
    '4sXGW4': 'Swirls',
    '4dlGRr': 'Boy',
    '4dXGD4': 'LSD Ufos',
    '4dfGW4': 'Volcano',
    '4sX3D4': 'Woodring',
    '4dX3WN': 'Chroma key',
    lsXGWN: 'Glowing Grid',
    lsX3W4: 'Mandelbrot - distance',
    ldf3DN: 'Mandelbrot - orbit traps',
    Xsf3DN: 'Math2GL - Sphere mapping',
    ldX3DN: 'Simple Eye Blower',
    ldX3D4: 'Simple Posterization',
    MsX3DN: 'Simple Sin Wave',
    '4dfGWN': 'Twister Thingy',
    XdX3WN: 'Plasma Triangle',
    XdX3W4: 'More Clouds',
    XdX3DN: 'Black Hole',
    Msf3W4: 'Math2CV-Edge scanner',
    Msf3WN: 'Procedural Disapproval',
    Msf3D4: 'Wobbly',
    MsXGD4: 'Dirty old CRT',
    MsX3WN: 'Raymarching example',
    Mdf3DN: 'Simple caustic',
    MdXGWN: 'Lit Sphere',
    MdX3DN: 'Transition: Fade',
    '4dsGW4': 'LED digits',
    '4ssGW4': 'Blah',
    '4sXGDN': 'Iterations - coral',
    '4dl3D4': 'Gravel',
    ldXGW4: 'Distorted TV',
    XssGDN: 'shroom test',
    XdsGD4: 'Rainbow Slices',
    XssGWN: 'Planet Funk',
    Xss3D4: 'AcidWobble',
    XslGDN: 'Downtown',
    Xsl3W4: 'Into the Darkness',
    '4slGD4': 'Mountains',
    '4slGWN': 'Pokeball',
    Xdl3W4: 'First attempt at this thing',
    '4dsGWN': 'Polaresian',
    '4dlGWN': 'Fly into Darkness',
    '4dlGDN': 'Noise blur',
    '4slGDN': 'Red Sphere Invasion',
    // https://www.shadertoy.com/results?query=&sort=newest&from=67152&num=12
    // 5597 / 5646
}
