export default {
    PoyGoZL5Lmmn9N5SF: `1. Jack-o'-lantern`,
    nL6YpkW8YvGKNEKtj: `2. point cloud vs spheres`,
    xxhTPvXjTWPCPLM2v: `3. Knotted Candy`,
    zd2E5vCZduc5JeoFz: `4. cubespace`,
    X74uYKiDLZJmqhLnh: `5. Planet Polygon`,
    xTf82BxK4LCcHNgq6: `6. Shadertoy Adapter`,
    hhsdvkiJ32bCTcezv: `7. blendy`,
    H65kA6jZ79o5qDjXG: `8. Block Party`,
    K9kkXT25juoLDcni4: `9. wip3`,
    '8eaHZkbv4GqCvTJJs': `10. eswng`,
    ixr3Pka4ChbtDzobh: `11. Spiral-Spring`,
    '9mqwFjEipb8pPtcPw': `12. ung`,
    wTaKE9X796qNFqgEM: `13. neurovelho`,
    PponkZdtktgJHhipC: `14. sbd`,
    DkQkxp558QrXdoDTs: `15. in(trouble)`,
    uqWtxuQpEkfxqWXCK: `16. wired`,
    TdqvseMQyoJ3ZrjrD: `17. Garden Fireworks`,
    RnwjSt42YXLcGjsgT: `18. morp`,
    h6BvsMWiHpgwT5Nhh: `19. pointsprite plasma`,
    '79HqSrQH4meL63aAo': `20. ball-o?3`,
    iQAtnkJRC8XtvT4tW: `21. synapsicorporation2`,
    xvg4vyvfWjCvKZQfW: `22. fuzeball`,
    ke5bF6hENE8zphaSp: `23. torus`,
    TGGLggjxQgLPEFHWx: `24. heightfield plotter`,
    WvKKxjSusH6cFyYcx: `25. neurovelho2`,
    XQQfnaTej5ZuzxNaf: `26. dyson`,
    bpN3ufoDGdkJjxFsQ: `27. starts`,
    aMJHfrjJHMKKy4iNi: `28. Glitter Spirals`,
    ChgRzRLbrFD5wzfZk: `29. galax-z`,
    XW2ueZpHcoWqtkuqD: `30. lorenz attractor`,
};
