
  /**
   * Entitas Generated Classes for test
   *
   * do not edit this file
   */
  module test {
    "use strict";

    import Pool = entitas.Pool;
    import Entity = entitas.Entity;
    import Matcher = entitas.Matcher;
    import ISystem = entitas.ISystem;
    import IMatcher = entitas.IMatcher;
    import IComponent = entitas.IComponent;
  
     export enum CoreComponentIds {
       Player,
       Position,
       View,
       Velocity,
       Movable,
       Destroy,
       Input,
       Interactive,
       Resource,
       Score,
       TotalComponents
      }

    Entity.initialize(CoreComponentIds.TotalComponents, undefined);
  
     export class PlayerComponent implements IComponent {
     }
     export class PositionComponent implements IComponent {
       public x:number;
       public y:number;
     }
     export class ViewComponent implements IComponent {
       public sprite:Object;
     }
     export class VelocityComponent implements IComponent {
       public x:number;
       public y:number;
     }
     export class MovableComponent implements IComponent {
     }
     export class DestroyComponent implements IComponent {
     }
     export class InputComponent implements IComponent {
       public x:number;
       public y:number;
     }
     export class InteractiveComponent implements IComponent {
     }
     export class ResourceComponent implements IComponent {
       public name:string;
     }
     export class ScoreComponent implements IComponent {
       public value:number;
     }
export class Pools {
  static _allPools:Array<Pool>;

  static get allPools():Array<Pool> {
    if (Pools._allPools == null) {
      Pools._allPools = [Pools.pool];
    }
    return Pools._allPools;
  }

  static _pool:Pool;

  static get pool():Pool {
    if (Pools._pool == null) {
      Pools._pool = new Pool(CoreComponentIds, CoreComponentIds.TotalComponents, false);
      entitas.viewer.VisualDebugging.init(Pools._pool);
    }

    return Pools._pool;
  }
}
}