var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
/**
 * Entitas Generated Classes for testgame
 *
 * do not edit this file
 */
var testgame;
(function (testgame) {
    "use strict";
    var Pool = entitas.Pool;
    var Entity = entitas.Entity;
    var CoreComponentIds;
    (function (CoreComponentIds) {
        CoreComponentIds[CoreComponentIds["DebugMessage"] = 0] = "DebugMessage";
        CoreComponentIds[CoreComponentIds["SingleDemo"] = 1] = "SingleDemo";
        CoreComponentIds[CoreComponentIds["TotalComponents"] = 2] = "TotalComponents";
    })(CoreComponentIds = testgame.CoreComponentIds || (testgame.CoreComponentIds = {}));
    Entity.initialize(CoreComponentIds.TotalComponents, { "entities": 128, "components": 64 });
    var DebugMessageComponent = /** @class */ (function () {
        function DebugMessageComponent() {
        }
        return DebugMessageComponent;
    }());
    testgame.DebugMessageComponent = DebugMessageComponent;
    var SingleDemoComponent = /** @class */ (function () {
        function SingleDemoComponent() {
        }
        return SingleDemoComponent;
    }());
    testgame.SingleDemoComponent = SingleDemoComponent;
    var Pools = /** @class */ (function (_super) {
        __extends(Pools, _super);
        function Pools() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        Object.defineProperty(Pools, "allPools", {
            get: function () {
                if (Pools._allPools == null) {
                    Pools._allPools = [Pools.pool];
                }
                return Pools._allPools;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(Pools, "pool", {
            get: function () {
                if (Pools._pool == null) {
                    Pools._pool = new Pool(CoreComponentIds, CoreComponentIds.TotalComponents, false);
                    entitas.viewer.VisualDebugging.init(Pools._pool);
                }
                return Pools._pool;
            },
            enumerable: false,
            configurable: true
        });
        return Pools;
    }(entitas.Pool));
    testgame.Pools = Pools;
})(testgame || (testgame = {}));
