/**
 * Entitas Generated Classes for testgame
 *
 * do not edit this file
 */
var testgame;
(function (testgame) {
    "use strict";
    var Pool = entitas.Pool;
    var Entity = entitas.Entity;
    var CoreComponentIds;
    (function (CoreComponentIds) {
        CoreComponentIds[CoreComponentIds["DebugMessage"] = 0] = "DebugMessage";
        CoreComponentIds[CoreComponentIds["SingleDemo"] = 1] = "SingleDemo";
        CoreComponentIds[CoreComponentIds["TotalComponents"] = 2] = "TotalComponents";
    })(CoreComponentIds = testgame.CoreComponentIds || (testgame.CoreComponentIds = {}));
    Entity.initialize(CoreComponentIds.TotalComponents, { "entities": 128, "components": 64 });
    var DebugMessageComponent = /** @class */ (function () {
        function DebugMessageComponent() {
        }
        return DebugMessageComponent;
    }());
    testgame.DebugMessageComponent = DebugMessageComponent;
    var SingleDemoComponent = /** @class */ (function () {
        function SingleDemoComponent() {
        }
        return SingleDemoComponent;
    }());
    testgame.SingleDemoComponent = SingleDemoComponent;
    var Pools = /** @class */ (function () {
        function Pools() {
        }
        Object.defineProperty(Pools, "allPools", {
            get: function () {
                if (Pools._allPools == null) {
                    Pools._allPools = [Pools.pool];
                }
                return Pools._allPools;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(Pools, "pool", {
            get: function () {
                if (Pools._pool == null) {
                    Pools._pool = new Pool(CoreComponentIds, CoreComponentIds.TotalComponents, false);
                    entitas.viewer.VisualDebugging.init(Pools._pool);
                }
                return Pools._pool;
            },
            enumerable: false,
            configurable: true
        });
        return Pools;
    }());
    testgame.Pools = Pools;
})(testgame || (testgame = {}));
